---
title: "Chapitre 12 : régression de Poisson"
layout: default
output: 
  html_document:
    css: styles.css
    toc: true
    toc_float: true
    layout: default
---


# Le modèle de Poisson

```{r}
Malaria <- read.table("poissonData3.csv", sep=",", header=T)
summary(Malaria)
```

```{r}
modP <- glm(N.malaria ~ Duree, data = Malaria, family = poisson)
modP
```

```{r}
plot(N.malaria ~ Duree, data = Malaria,pch=20,cex=0.5)
mod.lin <- lm(N.malaria ~ Duree, data = Malaria)
abline(a=coef(mod.lin)[1],b=coef(mod.lin)[2],lwd=2)
x <- seq(0,1500,by=1)
y <- exp(coef(modP)[1]+coef(modP)[2]*x)
lines(x,y,col="red",lty=2,lwd=2.5)

```



```{r}
modP3 <- glm( N.malaria ~ Duree + Sexe + Prevention, 
              data = Malaria,family = poisson )
```

# Tests et intervalles de confiance

```{r}
Malaria$Prevention <- relevel(Malaria$Prevention,ref="Rien")
modP3 <- glm( N.malaria ~ Duree + Sexe + Prevention, data = Malaria,
             family = poisson )
summary(modP3)
```

```{r}
modP2 <- glm( N.malaria ~ Duree + Sexe, data = Malaria, family = poisson)
-2*(logLik(modP2)-logLik(modP3))
qchisq(0.95,df=3)
```

```{r}
anova(modP2,modP3,test="LRT")
```

```{r message=FALSE, warning=FALSE}
library(car)
Anova(modP2,test="LR")
```

```{r}
round(confint.default(modP3),3)
round(confint(modP3),3)
```


# Sélection de variables


```{r message=FALSE, warning=FALSE}
Malaria <- read.table("poissonData.csv", sep=",", header=T)
Malaria1 <- na.omit(Malaria)
library(bestglm)
mod_sel <- bestglm(Malaria1,family=poisson)
mod_sel$BestModels
```

