---
title: "Chapitre 8 : Régression sous contraintes de norme : ridge, lasso, elastic net"
layout: default
output: 
  html_document:
    css: styles.css
#    toc: true
#    toc_float: true
    layout: default
---

```{r}
ozone <- read.table("ozone.txt",header=TRUE,sep=";",row.names=1)[,-c(11:12)]
ozone.X <- model.matrix(O3 ~ ., data = ozone)[,-1]
ozone.Y <- ozone$O3
```

```{r message=FALSE, warning=FALSE}
library(glmnet)
ridge <- glmnet(ozone.X, ozone.Y, alpha = 0)
lasso <- glmnet(ozone.X, ozone.Y)#par défaut alpha=1
en <- glmnet(ozone.X, ozone.Y, alpha = 0.5)
```

```{r}
plot(ridge,main="Ridge",ylim=c(-2,2))
plot(ridge,xvar="lambda",main="Ridge",ylim=c(-2,2))
plot(lasso,main="Lasso",ylim=c(-2,2))
plot(lasso,xvar="lambda",main="Lasso",ylim=c(-2,2))
plot(en,main="Elastic net",ylim=c(-2,2))
plot(en,xvar="lambda",main="Elastic net",ylim=c(-2,2))
```

```{r}
set.seed(1234)
cv.ridge <- cv.glmnet(ozone.X, ozone.Y, alpha = 0)
cv.lasso <- cv.glmnet(ozone.X, ozone.Y) #alpha=1 par défaut
cv.en <- cv.glmnet(ozone.X, ozone.Y, alpha = 0.5)
```

```{r}
cv.ridge$lambda.min
cv.ridge$lambda.1se
```

```{r}
plot(cv.ridge, main = "Ridge")
plot(cv.lasso, main = "Lasso")
plot(cv.en, main = "Elastic net")
```

```{r}
xnew <- ozone.X[c(25,30),]
rownames(xnew) <- NULL
```

```{r}
xnew
predict(cv.ridge,newx=xnew)
```

```{r}
ozone<-read.table("ozone.txt",header=TRUE,sep=";",row.names = 1)
ozone.X <- model.matrix(O3~.,data=ozone)
ozone.Y <- ozone$O3
cv.defaut <- cv.glmnet(ozone.X,ozone.Y)
lassodefaut<-glmnet(ozone.X,ozone.Y,lambda=cv.defaut$lambda.min)
```

```{r}
ozone$vent <- relevel(ozone$vent,ref="NORD")
ozone.X <- model.matrix(O3~.,data=ozone)
cv.nord <- cv.glmnet(ozone.X,ozone.Y)
lassonord <- glmnet(ozone.X,ozone.Y,lambda=cv.nord$lambda.min)
```

```{r}
predict(lassodefaut,ozone.X[1:4,])
predict(lassonord,ozone.X[1:4,])
```

```{r}
ozone.X <- model.matrix(O3~.-vent-nebulosite+C(vent,sum)+
                          C(nebulosite,sum),data=ozone)
cv.sum <- cv.glmnet(ozone.X,ozone.Y)
lassosum <- glmnet(ozone.X,ozone.Y,lambda=cv.sum$lambda.min)
predict(lassosum,ozone.X[1:4,])
```

