---
title: "Chapitre 5 : Inférence dans le modèle Gaussien"
layout: default
output: 
  html_document:
    css: styles.css
    toc: true
    toc_float: true
    layout: default
---



```{r}
ozone <- read.table("ozone.txt", header = T, sep = ";")
modele3 <- lm(O3 ~ T12 + Vx + Ne12, data = ozone)
resume3 <- summary(modele3)
coef3 <- coef(resume3)
IC3 <- t(confint(modele3, level = 0.95))
IC3
```

```{r}
library(ellipse)
par(mfrow=c(3,2))
for(i in 1:3){
  for(j in (i+1):4){
    plot(ellipse(modele3,c(i,j),level=0.95),type="l",
         xlab=paste("beta",i,sep=""),ylab=paste("beta",j,sep=""))
    points(coef(modele3)[i], coef(modele3)[j],pch=3)
    lines(c(IC3[1,i],IC3[1,i],IC3[2,i],IC3[2,i],IC3[1,i]),
          c(IC3[1,j],IC3[2,j],IC3[2,j],IC3[1,j],IC3[1,j]),lty=2)
  }
}
```

```{r}
c(resume3$sigma^2*modele3$df.res/qchisq(0.975,modele3$df.res),
  resume3$sigma^2*modele3$df.res/qchisq(0.025,modele3$df.res))
```


# Exemple 1 : la concentration en ozone

```{r}
modele3 <- lm(O3 ~ T12 + Vx + Ne12, data = ozone)
resume3 <- summary(modele3)
resume3
```

```{r}
modele2 <- lm(O3 ~ T12 + Vx, data = ozone)
anova(modele2, modele3)
```


# Exemple 2 : la hauteur des eucalyptus

```{r}
eucalypt <- read.table("eucalyptus.txt", header = T, sep = ";")
regsimple <- lm(ht ~ circ, data = eucalypt)
regM <- lm(ht ~ circ + I(sqrt(circ)), data = eucalypt)
anova(regsimple, regM)
```

```{r}
summary(regM)
```

```{r}
grille <- data.frame(circ = seq(min(eucalypt[,"circ"]),
                                max(eucalypt[,"circ"]), len = 100))
ICdte <- predict(regM,new=grille,interval="conf",level=0.95)
ICpre <- predict(regM,new=grille,interval="pred",level=0.95)
plot(ht ~ circ, data = eucalypt, pch="+", col="grey60")
matlines(grille,cbind(ICdte,ICpre[,-1]),lty=c(1,2,2,3,3),col=1)
legend("topleft", lty=2:3, c("E(Y)","Y"))
```


# Intervalle de confiance bootstrap

```{r}
modele3 <- lm(O3 ~ T12 + Vx + Ne12, data = ozone)
```

```{r}
resume3 <- summary(modele3)
resume3$coef[,1:2]
```

```{r}
res <- residuals(modele3)
ychap <- predict(modele3)
COEFF <- matrix(0, ncol = 4, nrow = 1000)
colnames(COEFF) <- names(coef(modele3))
ozone.boot <- ozone
```

```{r}
for(i in 1:nrow(COEFF)){
  resetoile <- sample(res, length(res), replace=T)
  O3etoile <- ychap + resetoile
  ozone.boot[,"O3"] <- O3etoile
  regboot <- lm(formula(modele3), data=ozone.boot)
  COEFF[i,] <- coef(regboot)
 }
```

```{r}
apply(COEFF, 2, quantile, probs = c(0.025,0.975))
```

```{r}
hist(COEFF[,"T12"], main = "", xlab = "Coefficient de T12")
```


